### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#11]
## Value Proposition
As a user I want to search for articles based on my own criteria
## Description
![description_step3a](https://user-images.githubusercontent.com/93940500/197538184-44b710e0-87eb-4541-bd4f-d6638bf2e070.png)
### User should be able to :
- [ ] see the list of articles as a result of his/her query
## Tasks
- [ ] fetch news from newsapi.org
- [ ] display found articles including image, title, author, description

**Comment by F-Kirchhoff** [comment]
Hey Thu, this is looking nice already, but please give more information about the functionality and the tasks: how to users go back? 
Also: is the fetching of news a user story by itself? Here you can decrease the size of your user stories!
Please remove the navigation bar + the search area from your wireframes, since they would not be useable at the moment. Only include elements in your App that serve a purpose.  (Don't try to think what might be useful in the future, only think what you need right now.)

**Comment by F-Kirchhoff** [comment]
Also: please be more precise what the "whole content" actually means, is it plain text, is it formatted with headings and paragraphs? Are images included?
