### ISSUE TITLE
Step 4

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#13]
## Value Proposition
As a user I want to read the whole content of a selected article
## Description
![description_step3b](https://user-images.githubusercontent.com/93940500/197540146-beb53d28-aad6-44bf-8cd4-ba2492fb72d6.png)
### User should be able to :
- [ ] read the full content of an article after clicking on it
## Tasks
- [ ] add an event listener on the title of each article
- [ ] on clicking on each title: the full content of article is fetched and displayed in the content page
