### ISSUE TITLE
Step 5

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#14]
## Value Proposition
As a user I want to have an area for my saved articles
## Description
![description_step5a](https://user-images.githubusercontent.com/93940500/197748233-c9609b5e-a75f-41d1-82d0-d98fc54672d9.png)
### User should be able to :
- [ ] visit an area where articles are saved
## Tasks
- [ ] add an item "Collections" to the navigation bar
- [ ] on visiting "Collection" a hard-coded article is shown
