### ISSUE TITLE
Step 6

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#15]
## Value Proposition
As a user I want to save the articles that i find interesting so that I can come back to them later
## Description
![description_step6](https://user-images.githubusercontent.com/93940500/197796431-3a85e0f8-fd41-4239-bb9e-68d922b4cdad.png)
### User should be able to :
- [ ] save their favourite articles after reading the full content
## Tasks
- [ ] add a "..." bookmark on the article on the full content page
- [ ] by clicking on this bookmark, the article is added to the collection page
- [ ] by clicking on an article title in the collection page, the full content of the article is display again in the content page, but this time the "..." bookmark is not to be seen
- [ ] add a "back" button on the collection page to return to the home page
