### ISSUE TITLE
Step 8

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#19]
## Value Proposition
As a user I want to have one or more collections of my favourite articles so that I can visit them again
## Description
![description_step8](https://user-images.githubusercontent.com/93940500/198965019-408825a1-fdcf-4050-88d5-896ac764fa32.png)
### User should be able to :
- [ ] create new collections
- [ ] add their favourite articles to any of the collections
- [ ] delete one or more articles from any collection
## Tasks
- [ ] starting point: the previous PR (userstory 7) already provides most of this Funktionalies applying Zustand
- [ ] in this implementation all the collections of articles is moved to datenbank
- [ ] the list of available of collections can be seen in the collections page
- [ ] upon reading an article in the content page, if the user click on the three vertical dots icon he can also see the lists of available collections in the popup Menu. Clicking on any of the collection, the article will be added there. If the user create here a new collection, the article will be automatically added to this collection
- [ ] In the collections page, whenever a user click on a collection, he can see all articles he added there before
- [ ] clicking on any of this article, the user can read the whole content again. 
- [ ] new feature: users can delete one or more articles in a collection by clicking on the remove icon next to the articles
