### ISSUE TITLE
Step 9

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#24]
## Value Proposition
As an user I want to highlight some texts in an article that I find especially interesting
## Description
<img width="521" alt="Screenshot 2022-11-03 at 10 56 59" src="https://user-images.githubusercontent.com/93940500/199692415-2fa7b9e6-38ab-46b6-8476-c6996b9d09d6.png">

### User should be able to :
- [ ] highlight a text with a mouse drag and it should stay there
- [ ] highlight several texts in an article
- [ ] remove highlights by double click on them
- [ ] highlights being made are preserved in the article for any future reading
## Tasks
- [ ] use range and selection
- [ ] pack a html element span around each range object
- [ ] style the span: background -> yellow, cursor -> pointer
- [ ] add a double click event listener to remove the style set before for highlighting
- [ ] update articles with highlights and save to database
