### ISSUE TITLE
Step 10

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#27]
## Value Proposition
As a user, I want to have one or more dashboards where I can pin my highlights being cut out from my favourite articles
## Description
![description_step10](https://user-images.githubusercontent.com/93940500/200199739-1a75d078-f179-4e86-88c9-a51d1114c38a.png)
### User should be able to: 
- [ ] see a dashboard page where collected highlights (which are "packed" in boxes) are lined up and one or more dropzone boards
- [ ] drag any highlight to any of the created board
- [ ] drag any of the highlights in any board back to the line of collected highlights
- [ ] choose any of the colors available in a given palette for the boxes background color
- [ ] read the whole highlight (if it is being clipped) by mouse dragging the box corner
## Tasks
- [ ] add Dashboard to the navigation bar
- [ ] on Dashboard page add a section for all the collected highlights (draggable zone), each included in a span and make it horizontally resizable
- [ ] add onContextMenu event for right-click
- [ ] add a color palette popped up by right-clicking any of the above span
- [ ] add some color patterns to the palette
- [ ] upon chosing (clicking on) a color pattern, the background of the respective span is set to the color of the chosen pattern
- [ ] make each span draggable: set draggable =true, add onDragOver event
- [ ] make the draggable zone also droppable: add onDrop, onDragOver events to the section
- [ ] add a dropzone as a board, make it droppable: add onDragOver, onDrop
- [ ] add "Add board" button to create more dropzone/board
- [ ] add icon "-"  and the respective event handler for removing the board
