### ISSUE TITLE
Step 1

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#3]
## Value Proposition
As a user I want to find interesting articles based on my criteria 
### User should be able to :
- [ ] search for news/articles/columns based on given criteria. For example themes, news sources, when they were published (from -> to), languages, countries etc.
- [ ] see all the results
## Tasks
- [ ] create a vertical navigation bar on the left with the first item "Query" 
- [ ] create a container for different input fields like "keywords", "source", "published at", "language", "country", a "sorted by" drop down list and a "search" button
- [ ] pass input values to parameters for the request url
- [ ] fetch data
- display first 20 results
