### ISSUE TITLE
Step 11

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#31]
## Value Proposition
As a user, I want to see all selections that I had made in favourite articles, and pin them in one or more board
## Description
![description_step11](https://user-images.githubusercontent.com/93940500/201134741-af565dea-4910-412b-967f-34b4572baa89.png)

### On the dashboard page user should be able to: 
- [ ] see all the selections they had made in their favourite articles
- [ ] drag any selection to a board
## Tasks
- [ ] update articles with selections to database
- [ ] load all selections from database to the draggable section in dashboard page
- [ ] add a save icon to the dropzone section
- [ ] upon clicking the save icon:
- [ ] [ ] the dashboard will be posted to database
- [ ] [ ] the dropzone is cleared
- [ ] add a link "go here to see the dashboards you have saved" to another page where users can see their saved boards
