### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#4]
## Value Proposition
As I am allergic to mainstream media, I want to build a webpage for collecting articles and columns from newspapers around the world so that the news inputs can be narrowed down to one's interest. 
### User should be able to :
- [ ] search for news/articles/columns based on themes, news sources, when they were published (from -> to), languages, countries etc.
- [ ] from query results, users can add articles they are interested in in their own collections
- [ ] a user can have as many collections as he/she wishes. Each collection behaves like a playlist where user can decide on name and description (optional) of the playlist
- [ ] from the collections of their own, users can write down notices and mark favourite paragraphs in each collected article
- [ ] user can also create as their own dashboards (as many as they want), on which they can "paste" their notices and excerpts (the marked paragraph) from different collected articles 
## Tasks
- [ ] create a vertical navigation bars with the first item "Query"
- [ ] on Click on "Query": open a Form with input text fields with respective labels like "keywords", "source", "published at", "language", "country" and a "search" button as well as a "sorted by" drop down list
- [ ] on Click on "search": display first 20 results in the same window as the above mentioned Form
- [ ] add a "load more" button to load more results. Each load is limited to 20 results
- [ ] add a "..." button at the top right corner of each article
- [ ] on Click on "..." : a form popped up in which all existing collections are listed. A button "new collection" is also included in the form
- [ ] on Click on "new collection": a form popped up where user can enter name and description (optional) of the new collection in the respective input text fields
- [ ] as long as a collection is created, its name appears on the navigation bar. On click on the name the collection is shown
- [ ] as long as a collection is created, item "Dashboard" is added to the navigation bar
- [ ] on Click on "Dashboard": a dashboard window is opened to the user. In this window, all the marked und/oder notices (included in boxes), a "board" as well as a "add dashboard" button will be visible to the user. The user can drag any box and drop on the board
- [ ] the user can add more dashboard by clicking the button "add dashboard"
