### ISSUE TITLE
Step 2

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#5]
## Value Proposition
As a user I want to read the whole content of an article so that I can have more information
## Description
![description_step2](https://user-images.githubusercontent.com/93940500/196633959-9c6cd3c8-499d-4d30-a3d8-0a029318abeb.png)
### User should be able to :
- [ ] read the whole article after choosing (clicking on) one
- [ ] go back to the main window where they see all other articles
## Tasks
- [ ] lay out dummy data as a list of objects
- [ ] display texts element from each objects in the form of a card list
- [ ] create an event onClick on each card (article)
- [ ] create a handler for the event onClick to open a window where the whole content of the article is visible for the user
- [ ] add a "Back" button, a onClick event and an event handler to switch back to the main window where all articles are
- [ ] move the dummy data above to a dummy database
- [ ] implement server-side rendering
