### ISSUE TITLE
Step 7

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#6]
## Value Proposition
As a user I want to have one or more collections of my favourite articles
## Description
![description_step7](https://user-images.githubusercontent.com/93940500/198266131-9a4c5bbc-4562-46f7-bc59-043f5e3b4209.png)
### User should be able to :
- [ ] create new collections
- [ ] add their favourite articles to any of the collections
## Tasks
- [ ] starting point: we are now at the content page where the full content of an article is to be seen. On the right side, top of the article, there is an three vertical dots
- [ ] on clicking on the three vertical dots icon on the content page : a menu is popped up
- [ ] list all the existing collections in the popup menu and a "create new collection" button
- [ ] on clicking the button "create new collection": a new collection is added and listed on the menu
- [ ] on clicking any of the collection: the article is added to the collection
- [ ] on switching to the collections page ("collections" on the navigation bar): all the created collections are listed
- [ ] next to each collection there is a "x" icon
- [ ] on clicking on "x" icon: the corresponding collection is removed
- [ ] on clicking on each collection: a collection page is open displaying all the articles that were added to this collection
