### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by anhthu253** [anhthu253/capstone-project#7]
## Value Proposition
As a user I want to search for articles based on my own criteria
## Description
![description_step1](https://user-images.githubusercontent.com/93940500/196215840-e3fccf32-07a8-4850-918c-82030bc087b1.png)
### User should be able to :
- [ ] search for articles by thema (eg. politics, sport), sources (eg. politico, the new york times), the period when they published (from..to), countries
## Tasks
- [ ] add a form which includes text inputs for given criteria (thema, sources, period, countries) and a search button
- [ ] take the input values as parameters for the API key
- [ ] fetch data from the dummy database
- [ ] display results
